modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/dantaeusb-mc/Zetter/issues"

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/zetter-painting-mod"
updateJSONURL="https://api.modrinth.com/updates/ZmLgjf6f/forge_updates.json"
logoFile="zetter.png"
credits='''
StuarteLitro/@ppblitto for fancy icons and Portuguese translation
diesieben07#0714 from Forge Discord for absolutely insane amount of help
gigaherz#9173 from Forge Discord for consultations about Forge and GUI
XFactHD#5288 from Forge Discord for help on fixing issues further into the development

ItamarDenkberg for Hebrew translation
iSrNinja for Spanish translation
DrHesperus for Russian translation
Vakarian89 for Polish translation
cream280 for Chinese translation
OttovonBismarckderErste for German translation
StickManBro for Dutch translation

Pxlsamosa for art commissions and mod art
Eliathx for art commissions

Forge Discord special thanks:
Cyborgmas#0379
Amethyst#6998
Kovak#5505
Woodland Creature#3144
ChampionAsh5357#5519
Commoble#9251
Lemongradle (sciwhiz12#1286)

Examples and references:
greyminecraftcoder and all MinecraftByExample contributors
Vazkii and Quark team for opening their source code as I often used it as a reference
'''

authors="Dmitry Burlakov <dantaeusb@live.com>"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"